export ZSH="~/.oh-my-zsh"

ZSH_THEME="nebirhos"
plugins=(git python git-extras jsontools repo sudo ansible)
source $ZSH/oh-my-zsh.sh
export EDITOR=nvim
export VISUAL=nvim
alias vi=nvim
alias vim=nvim
alias v=nvim
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP
export HISTTIMEFORMAT=${HISTTIMEFORMAT:-"%Y-%m-%d %H:%M:%S"}
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
export HISTFILESIZE=$HISTSIZE
alias pirate='tmux new-session /mnt/c/Users/memog/src/venvs/.venv/bin/pirate-get -C "aria2c ''%s'' -d /mnt/c/Users/memog/Downloads     --seed-time=0"'
alias doc-fzf='/mnt/c/Users/memog/src/venvs/.venv/bin/doc-fzf'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
LS_COLORS=$LS_COLORS:'ow=1;34:' ; export LS_COLORS
export PATH=$PATH:~.local/bin
cd ~